#!/bin/bash

MODKEY=Mod4

export WMII_TERM='urxvt'

#Colors
export WMII_BACKGROUND='#4f5459'
export WMII_NORMCOLORS='#ffffff #3e3e3e #3e3e3e'
export WMII_FOCUSCOLORS='#ff9966 #333333 #333333'
export WMII_URGENTCOLORS='#333333 #dea61c #dea61c'

STATUS_MSG_COLOR='#ffffff #333333 #333333'
WARN_MSG_COLOR='#b36b47 #333333 #333333'

export WMII_FONT='xft:DejaVu Sans Mono:size=7:antialias=true:autohint=true'

#icons
VOLTAGE_ICON="⚡"
SUN_ICON="☀"
RAIN_ICON="☔"
CLOUD_ICON="☁"
VOLUME_ICON="♪"
CLOCK_ICON="◷"
MUSIC_ICON="►"
V4_ICON="♶"
V6_ICON="♸"
LAN_ICON="☍"
WLAN_ICON="☫"
UPLOAD_ICON="↗"
DOWNLOAD_ICON="↙"
QUALITY_ICON="⌔"
LOCK_ICON="☠"

#Tags
wmiir write /tagrules <<!
/Screen Layout Editor/ -> ~
/MPlayer.*/ -> ~+mpl
/.*VLC media player.*/ -> ~+vlc
/mutt/ -> mail
/.*Claws Mail.*/ -> mail
/.*Thunderbird.*/ -> mail
/.*Lanikai.*/ -> mail
/weechat-curses/ -> irc
/.*EasyTAG.*/ -> tag
/.*LibreOffice.*/ -> wrt
/.*Amazon MP3.*/ -> ~+mp3
/.*Minecraft.*/ -> mcr
/.*Chromium.*/ -> www
/.*Chrome.*/ -> www
/.*Opera.*/ -> www
/.*Firefox.*/ -> www
/.*NetBeans.*/ -> dev
/.*Anjuta.*/ -> dev
/.*CodeLite.*/ -> dev
/.*IntelliJ IDEA.*/ -> dev
/.*VirtualBox.*/ -> vir
/CSSH.*/ -> ssh
/VBA/ -> vba
/.*ncmpcpp.*/ -> mpd
/.*JDownloader.*/ -> ~+jdl
/.*tabbed-0.3.*/ -> www
/.*mupdf.*/ -> pdf
/.*FileZilla.*/ -> ~+ftp
/.*Servermanager.*/ -> ~+ftp
/.*mypaint.*/ -> pnt
/.*MyPaint.*/ -> pnt
/.*wine.*/ -> win
/.*Wine.*/ -> win
/.*rdesktop.*/ -> win
/urxvt/ -> con
/.*OpenTTD.*/ -> ttd
/Transmission/ -> tor
/qBittorrent.*/ -> tor
/.*Rubyripper.*/ -> rip
/.*Wireshark.*/ -> wsh
/.*Gimp.*/ -> ~+gmp
/.*/ -> sel
/.*/ -> 1
!

xbindkeys &

#Status
status() {
    echo -n "$STATUS_MSG_COLOR $CLOCK_ICON $(date +'%d%m%Y %H:%M:%S')"
}

#volume
volume() {
    VOLUME="$(amixer get Master | tail -n 1 | grep -o '[0-9]\?[0-9]\?[0-9]%')"
    echo "$STATUS_MSG_COLOR $VOLUME_ICON $VOLUME" | wmiir create /rbar/zz_volume
    
    wmiir read /event |
    while read wi_event; do
        case $wi_event in
            "RightBarClick 5 zz_volume"*)
                VOLUME="$(amixer set Master 3%- | tail -n 1 | grep -o '[0-9]\?[0-9]\?[0-9]%')"
            ;;
            "RightBarClick 4 zz_volume"*)
                VOLUME="$(amixer set Master 3%+ | tail -n 1 | grep -o '[0-9]\?[0-9]\?[0-9]%')"
            ;;
        esac
        echo -n "$VOLUME_ICON $VOLUME" | wmiir write /rbar/zz_volume 2>/dev/null
    done

    wmiir rm /rbar/zz_volume
}
(volume & ) &

#slock
lock() {
    echo "$STATUS_MSG_COLOR $LOCK_ICON" | wmiir create /rbar/zzz_lock
    RIGHT_MOUSE_DOWN=false

    wmiir read /event |
    while read wi_event; do
        case $wi_event in
            "RightBarClick 1 zzz_lock"*)
                if $RIGHT_MOUSE_DOWN
                then
                    shutdown -hP now
                else
                    slock
                fi
            ;;
            "RightBarClick 2 zzz_lock"*)
                if $RIGHT_MOUSE_DOWN
                then
                    pm-hibernate
                fi
            ;;
            "RightBarMouseDown 3 zzz_lock"*)
                RIGHT_MOUSE_DOWN=true
            ;;
            "RightBarClick 3 zzz_lock"*)
                RIGHT_MOUSE_DOWN=false
            ;;
        esac
    done
}
(lock &) &

#mpd
mpd_stats() {
    sleep 10
    while true; do
        MPC=`mpc status`
        SONG=`echo "$MPC" | grep -o -E "(.*\-.*)" | sed 's/^.*: //'`
        TIME=`echo "$MPC" | grep -o -E "[0-9]+:[0-9]{2}/[0-9]+:[0-9]{2}"`

        if [ -z "$SONG" ]; then
            wmiir remove /rbar/00_mpd &> /dev/null
        else
            echo "$STATUS_MSG_COLOR $MUSIC_ICON ${SONG}[$TIME]" | wmiir create /rbar/00_mpd
        fi
        sleep 1
    done
}
#(mpd_stats &) &

#moc
moc_stats() {
    sleep 10
    while true; do
        MOC=$(mocp -Q "%file (%tl)" 2> /dev/null | sed 's/^.*\///g; s/\.mp3//g');

        if [ -z "$MOC" ]; then
            wmiir remove /rbar/00_mpd &> /dev/null
        else
            echo "$STATUS_MSG_COLOR $MUSIC_ICON $MOC" | wmiir create /rbar/00_mpd
        fi
        sleep 5
    done
}
#(moc_stats &) &

#lastfm
lastfm() {
    sleep 10
    while true; do
        SONG=$(~/bin/now_playing "%ARTIST% - %TITLE%" 2> /dev/null)
        if [ -z "$SONG" ]; then
            wmiir remove /rbar/00_mpd &> /dev/null
        else
            echo "$STATUS_MSG_COLOR $MUSIC_ICON $SONG" | wmiir create /rbar/00_mpd
        fi
        sleep 5
    done
}
(lastfm &) &

#weather
weather() {
    while true; do
        LOCATION=$(geoiplookup $(curl -4 -s ip.dev-urandom.eu 2>/dev/null) 2>/dev/null | grep -m 1 -P -o '[0-9]?[0-9]\.[0-9]*, [0-9]?[0-9]\.[0-9]*' | sed 's/ /%20/')
        WOEID=$(curl -s "http://where.yahooapis.com/geocode?location=$LOCATION&flags=xml&gflags=R&appid=dHxQNb4m" 2>/dev/null | grep -o '<woeid>.*</woeid>' | sed 's/\(<woeid>\)\|\(<\/woeid>\)//g')
        WEATHER=`curl -s "http://weather.yahooapis.com/forecastrss?u=c&w=$WOEID" | grep "<yweather:condition" | perl -pe 's/.*text=\"(.*?)\".*temp=\"(\-?\d*)\".*/$2°C - $1/g'`
         
        case $WEATHER in
            *Sun*)
                echo "$STATUS_MSG_COLOR $SUN_ICON $WEATHER" | wmiir create /rbar/01_weather
            ;;
            *Rain*)
                echo "$STATUS_MSG_COLOR $RAIN_ICON $WEATHER" | wmiir create /rbar/01_weather
            ;;
            *Cloud*)
                echo "$STATUS_MSG_COLOR $CLOUD_ICON $WEATHER" | wmiir create /rbar/01_weather
            ;;
            *)
                echo "$STATUS_MSG_COLOR $WEATHER" | wmiir create /rbar/01_weather
            ;;
        esac
        sleep 640
    done
}
(weather &) &

#lan
lan() {
    while true; do
        LAN="$(ifconfig eth0 | grep 'inet ' | awk '{ print $2}')"
        if [ -n "$LAN" ]
        then
            DOWNLOAD=$(ifconfig eth0 | grep 'RX packets' | awk '{print $6,$7}' | sed 's/(\|)//g')
            UPLOAD=$(ifconfig eth0 | grep 'TX packets' | awk '{print $6,$7}' | sed 's/(\|)//g')
            echo "$STATUS_MSG_COLOR $LAN_ICON $LAN $DOWNLOAD_ICON $DOWNLOAD $UPLOAD_ICON $UPLOAD" |  wmiir create /rbar/02_lan &> /dev/null
        else
            wmiir remove /rbar/02_lan &> /dev/null
        fi
        sleep 30
    done
}
(lan &) &

#wlan
wlan() {
    while true; do
        RFLIST=`rfkill list`
        case $RFLIST in
            *yes*)
                wmiir remove /rbar/02_wlan &> /dev/null
            ;;
            *)
                WLAN=$(ifconfig wlan0 | grep 'inet ' | awk '{ print $2}')
                if [ -n "$WLAN" ]
                then
                    QUALITY=$(iwconfig wlan0 | awk -F/ '/Link Quality=/ { gsub("Link Quality=",""); print $1; }' | tr -d ' ')
                    DOWNLOAD=$(ifconfig wlan0 | grep 'RX packets' | awk '{print $6,$7}' | sed 's/(\|)//g')
                    UPLOAD=$(ifconfig wlan0 | grep 'TX packets' | awk '{print $6,$7}' | sed 's/(\|)//g')
                    echo "$STATUS_MSG_COLOR $WLAN_ICON $WLAN $DOWNLOAD_ICON $DOWNLOAD $UPLOAD_ICON $UPLOAD $QUALITY_ICON $QUALITY" | wmiir create /rbar/02_wlan &> /dev/null
                else
                    echo "$WARN_MSG_COLOR $WLAN_ICON ON" | wmiir create /rbar/02_wlan &> /dev/null
                fi
            ;;
        esac
        sleep 30
    done
}
(wlan & ) &

#ip
ip() {
    while true; do
        IPV4="$(curl -4 ip.dev-urandom.eu 2> /dev/null)"
        IPV6="$(curl -6 ip.dev-urandom.eu 2> /dev/null)"

        if [ -n "$IPV4" ]
        then
            echo "$STATUS_MSG_COLOR $V4_ICON $IPV4" |  wmiir create /rbar/03_ipv4 &> /dev/null
        else
            wmiir remove /rbar/03_ipv4 &> /dev/null
        fi

        if [ -n "$IPV6" ]
        then
            echo "$STATUS_MSG_COLOR $V6_ICON $IPV6" |  wmiir create /rbar/04_ipv6 &> /dev/null
        else
            wmiir remove /rbar/04_ipv6 &> /dev/null
        fi
        
        sleep 320
    done
}
(ip &) &

#battery
bat() {
    while true; do
	BAT=$(acpi -b | awk '{print $4}' | sed 's/,//')
        case $BAT in
            *100*)
                wmiir remove /rbar/05_bat &> /dev/null
            ;;
            *)
                echo "$WARN_MSG_COLOR $VOLTAGE_ICON $BAT" | wmiir create /rbar/05_bat &> /dev/null
            ;;
        esac
        sleep 320
    done
}
(bat &) &

(dropbox start &) &
